* Liberating the Humanities: Toward an Ethics of Software

#+BEGIN_VERSE
Scott Dexter, Professor of Computer Science, Brooklyn College
Erin Glass, Digital Fellow and English doctoral student, CUNY Graduate Center
Evan Misshula, Manager of the Tech Talent Pipeline, Queens College
#+END_VERSE

The digital humanities rely, fundamentally, on software. And while
digital humanists can be very explicit about the ethical positions
embedded in their scholarship, pedagogy, and other academic labor, the
software we use can appear to be completely orthogonal--neutral, if
not simply irrelevant--to these concerns. 

Of course, some DHers do make software choices based on ethical
considerations--for example, perceiving and acting on a direct
connection between, on one hand, a felt scholarly imperative for
sharing and transparency, and, on the other, their use and creation of
open-source software. At the same time, while
freely available “Web 2.0” technologies such as Twitter, Facebook, and
Google Docs offer educators exciting opportunities to foster energetic
forms of student collaboration, these tools deprive students of rights
over their data and foster a passive, consumer-oriented relationship
toward technology. 

How should we choose the technologies we use in our teaching and research?
As we increasingly integrate  digital technologies into our 
practice, we need a critical framework for analyzing the ethical and
social implications of their use. That is, we must move this kind of ethical deliberation
from the narrow scope of individual choice to a broader discussion of
software ethics within the digital humanities community.


 In this piece, we  offer both tools and controversial positions:

- a primer on software ethics, especially the implications of “free
  software,” “open-source” software, and proprietary software;

- an “environmental scan” of common DH software practices;

- recommendations for making more
  ethically-informed software choices, including an on-ramp for
  scholars and institutions who are more comfortable with incremental,
  rather than wholesale, change;

- a call for funders to be explicit about software ethics in their
  RFPs; and

- a vision for a digital humanities,
  and an academy, which is fully conscious of the ethical implications
  of the software it both produces and relies upon.


